### ISSUE TITLE
Where is issue #23?

### ISSUE THREAD

**Issue by BuildMonkey** [alembic/cask#11]
I am having a problem that issue #23 should resolve: not preserving properties. This error is occurring in cask version 1.0.2. I would like to know if the version I am on has the fix for issue #23. I didn't see any info on this issue, so logging to confirm.

Thanks!

**Comment by rsgalloway** [comment]
Hi, latest version is 1.1.1 (if you clone from github). There's a unit test for issue #23 and it's passing for me. Can you try 1.1.1 and see if the issue remains for you?

**Comment by BuildMonkey** [comment]
Can I use version 1.1.1 with alembic 1.7.2?

**Comment by rsgalloway** [comment]
I'm not sure why that would be a problem. Have you tried it?

**Comment by BuildMonkey** [comment]
Hello-

No due to some publishing of new packages our side. Using the latest
version was not my initial query but rather in which version of cask was
the fix introduced. Are you able to provide me with that answer?

Regards,
Rita

**Comment by rsgalloway** [comment]
Looks like it was addressed in 0.9.5a with this commit: https://github.com/rsgalloway/alembic/commit/36428aff25dd8df6c270cc28e2c21854c1040814

**Comment by BuildMonkey** [comment]
Hello-

Thank you for the clarification. I am observing the problem still in 1.0.2,
and will report if the behaviour continues with the latest version.
